import os
import json
import pygame

from config.classes import Tile


def set_display(width, height, name):
    """Sets the window dimensions and title."""
    screen = pygame.display.set_mode((width, height))
    pygame.display.set_caption(name)
    return screen, width, height


def get_sprite(sheet, x, y, width, height):
    """Extracts a single surface from a spritesheet."""
    sprite = pygame.Surface([width, height], pygame.SRCALPHA)
    sprite.blit(sheet, (0, 0), pygame.Rect(x, y, width, height))
    return sprite


def _is_tile_mostly_transparent(tile_surf: pygame.Surface, *, alpha_threshold: int = 10, max_solid_ratio: float = 0.01) -> bool:
    """
    Returns True if the tile is basically empty.
    - alpha_threshold: count pixels with alpha > this as "solid"
    - max_solid_ratio: if solid_pixels/total_pixels <= this => empty
    """
    w, h = tile_surf.get_size()
    total = w * h
    if total <= 0:
        return True

    # Fast-ish per-pixel alpha check without extra dependencies
    solid = 0
    for y in range(h):
        for x in range(w):
            if tile_surf.get_at((x, y)).a > alpha_threshold:
                solid += 1
                if (solid / total) > max_solid_ratio:
                    return False
    return True


def load_tileset_named_library(
    tileset_path: str,
    *,
    tile_size: int = 16,
    target_size: int = 48,
    name_prefix: str = "vania",
    collides_local_ids: set[int] | None = None,
    skip_empty: bool = True,
) -> dict[str, dict]:
    """
    Base library with stable autogenerated names: vania_000, vania_001, ...

    If skip_empty=True, tiles that are mostly transparent are not added to the dictionary.
    (The index numbers still follow the sheet order, so aliases like 'vania_064' remain valid.)
    """
    collides_local_ids = collides_local_ids or set()

    sheet = pygame.image.load(tileset_path).convert_alpha()
    tile_library: dict[str, dict] = {}

    i = 0
    for y in range(0, sheet.get_height(), tile_size):
        for x in range(0, sheet.get_width(), tile_size):
            tile_name = f"{name_prefix}_{i:03d}"
            raw = get_sprite(sheet, x, y, tile_size, tile_size)

            if skip_empty and _is_tile_mostly_transparent(raw):
                i += 1
                continue

            img = pygame.transform.scale(raw, (target_size, target_size))

            tile_type = "solid" if i in collides_local_ids else "ground"
            tile_library[tile_name] = {"image": img, "tile_type": tile_type}
            i += 1

    return tile_library
